version: '3'

services:
    app:
        container_name: filament-template
        build:
            context: ./docker
            dockerfile: Dockerfile
        user: "1000"
        tty: true
        working_dir: /var/www
        environment:
            OTEL_SERVICE_NAME: 'laravel_api_service'
            OTEL_PHP_AUTOLOAD_ENABLED: true
            OTEL_TRACES_EXPORTER: otlp
            #      OTEL_METRICS_EXPORTER: otlp
            OTEL_LOGS_EXPORTER: otlp
            OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
            OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
            OTEL_PROPAGATORS: baggage,tracecontext
        volumes:
            - '.:/var/www'
            #            - './docker/supervisor/supervisord.app.conf:/etc/supervisor/conf.d/octane.conf'
            - './docker/php.ini:/usr/local/etc/php/php.ini'
            #    command: ["supervisord","-n", "-c", "/etc/supervisor/conf.d/octane.conf"]
        networks:
            - developer-net

    nginx:
        image: 'nginx:1.19.8-alpine'
        container_name: nginx-server
        tty: true
        ports:
            - '8100:80'
        working_dir: /var/www
        volumes:
            -  './docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf'
            #      -  './docker/nginx/conf/swoole.conf:/etc/nginx/conf.d/conf.conf'
            - '.:/var/www'
        depends_on:
            - app
        networks:
            - developer-net

#    redis:
#        image: redis:7.0.11
#        container_name: redis-server
#        networks:
#            - developer-net

    postgre:
        image: postgres:16.1-alpine
        container_name: postgre-db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: filament
        volumes:
            - ./data/postgre:/var/lib/postgresql/data
        ports:
            - 5001:5432
        networks:
            - developer-net

    mariadb:
        image: mariadb:10.11.7
        container_name: maria-db
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_USER: mariadb
            MYSQL_PASSWORD: secret
            MYSQL_DATABASE: filament
        volumes:
            -  ./data/mariadb:/var/lib/mysql:Z
        ports:
            -   5002:3306
        networks:
            - developer-net

networks:
    developer-net:
        external: true
